# Generated by Django 5.2.3 on 2025-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('equipment', models.CharField(max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
