# Generated by Django 5.2.3 on 2025-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_voicenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='weight',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='exercise',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='reps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='sets',
            field=models.IntegerField(),
        ),
    ]
