# Generated by Django 5.2.3 on 2025-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_workoutlog_weight_workoutlog_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='reps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='sets',
            field=models.PositiveIntegerField(),
        ),
    ]
